resource_group_name                = "terraform_ppd"
storage_account_name               = "ghactionteststorageppd"
location                           = "East US"
search_serivce_name                = "searchservice-ppd5050"
search_serivce_sku                 = "standard"
web_app_service_plan_name          = "web-app-service-plan-ppd"
web_app_service_plan_sku_name      = "F1"
