resource_group_name                = "terraform_dev"
storage_account_name               = "ghactionteststoragedev"
location                           = "East US"
search_serivce_name                = "searchservice-dev5050"
search_serivce_sku                 = "standard"
web_app_service_plan_name          = "web-app-service-plan-dev"
web_app_service_plan_sku_name      = "Free"
