storage_account_name = "ghactionteststoragedev"
location             = "East US"
rgname               = "github-action-dev"
search_serivce_name  = "searchservice-dev"
search_serivce_sku   = "standard"
