name: 'Terraform'

on:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: dev

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Terraform
      run: |
        sudo apt-get update && sudo apt-get install -y wget unzip
        wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        unzip terraform_1.5.7_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform -version

    - name: 'Terraform Format'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: "./iac"
        
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./iac"

    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: "./iac"
        
#    - name: 'Terraform Plan'
 #     uses: hashicorp/terraform-github-actions@master
  #    with:
  #      tf_actions_version: 0.14.8
  #      tf_actions_subcommand: 'plan'
  #      tf_actions_working_dir: "./iac"
  #      terraform_arguments: '-out=out.tfplan'

    - name: 'Terraform Plan'
      run: |
        terraform -chdir=./iac plan -out=tfplan
      env:
        TF_IN_AUTOMATION: "true"
        
    - name: Upload the plan
      uses: actions/upload-artifact@v4.6.0
      with:
        name: tfplan
        path: ./iac/out.tfplan    

          
#    - name: Terraform Apply
#      if: github.ref == 'refs/heads/main'
#      uses: hashicorp/terraform-github-actions@master
#      with:
#        tf_actions_version: 0.14.8
#        tf_actions_subcommand: 'apply'
#        tf_actions_working_dir: "./iac"
