name: 'Terraform'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Terraform
      run: |
        sudo apt-get update && sudo apt-get install -y wget unzip
        wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        unzip terraform_1.5.7_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform -version

    - name: 'Terraform Init'
      run: |
        terraform -chdir=./iac init -input=false

    - name: 'Terraform Format'
      run: |
        terraform -chdir=./iac fmt

    - name: 'Terraform Validate'
      run: |
        terraform -chdir=./iac validate

    - name: 'Terraform Plan'
      run: |
        terraform -chdir=./iac plan -out=tfplan
      env:
        TF_IN_AUTOMATION: "true"

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: ./iac/tfplan
